# Generated before configuration, outside the checkout, by release tooling.
# Empty is an ordinary development build: the offline dialog reports unavailable data.
set(PIXELVIEW_LICENSE_DATA_DIR "" CACHE PATH "Directory containing generated Pixelview license metadata")
if(PIXELVIEW_LICENSE_DATA_DIR)
  cmake_path(ABSOLUTE_PATH PIXELVIEW_LICENSE_DATA_DIR NORMALIZE OUTPUT_VARIABLE _pixelview_license_dir)
  foreach(_pixelview_license_name IN ITEMS third-party-notices.txt source-manifest.json)
    set(_pixelview_license_file "${_pixelview_license_dir}/${_pixelview_license_name}")
    if(NOT EXISTS "${_pixelview_license_file}" OR IS_DIRECTORY "${_pixelview_license_file}")
      message(FATAL_ERROR "Missing generated Pixelview license asset: ${_pixelview_license_file}")
    endif()
    file(SIZE "${_pixelview_license_file}" _pixelview_license_size)
    if(_pixelview_license_size EQUAL 0)
      message(FATAL_ERROR "Empty generated Pixelview license asset: ${_pixelview_license_file}")
    endif()
    if(OS_MACOS)
      target_sources(obs-studio PRIVATE "${_pixelview_license_file}")
      set_property(SOURCE "${_pixelview_license_file}" PROPERTY MACOSX_PACKAGE_LOCATION "Resources/license")
      source_group("Resources/license" FILES "${_pixelview_license_file}")
    else()
      target_add_resource(obs-studio "${_pixelview_license_file}" "${OBS_DATA_DESTINATION}/obs-studio/license")
    endif()
  endforeach()
  unset(_pixelview_license_dir)
  unset(_pixelview_license_file)
  unset(_pixelview_license_name)
  unset(_pixelview_license_size)
endif()
