#!/usr/bin/env python3
"""Regenerate embedded, synthetic-only CC0 capability fixtures; test tool only.
No encoder, ffmpeg binary, software decoder, or file IO is needed at runtime.
"""
import hashlib
import json
import re
from pathlib import Path
import struct
import subprocess

ROOT = Path(__file__).resolve().parents[1]
WORK = ROOT / '.test-build/capability-fixtures'
WORK.mkdir(parents=True, exist_ok=True)
rows = []
header = ['/* Generated by tests/generate-capability-fixtures.py. Synthetic testsrc2',
          ' * compressed data dedicated to CC0-1.0. No third-party media. */']
for name, codec, pixel, profile in [('h264', 'h264', 'yuv420p', 'baseline'),
        ('main', 'hevc', 'yuv420p', 'main'), ('main10', 'hevc', 'yuv420p10le', 'main10'),
        ('vp9_0', 'vp9', 'yuv420p', '0'), ('vp9_2', 'vp9', 'yuv420p10le', '2')]:
    path = WORK / (name + ('.ivf' if codec == 'vp9' else '.' + codec))
    command = ['ffmpeg', '-hide_banner', '-loglevel', 'error', '-y', '-f', 'lavfi', '-i',
               f'testsrc2=size=192x108:rate=60,scale=1920:1080:flags=neighbor,format={pixel}',
               '-frames:v', '3', '-color_range', 'tv', '-colorspace', 'bt709',
               '-color_trc', 'bt709', '-color_primaries', 'bt709']
    if codec == 'h264':
        command += ['-c:v', 'libx264', '-preset', 'ultrafast', '-profile:v', profile,
                    '-level:v', '4.2', '-x264-params', 'bframes=0:keyint=3:threads=1:force-cfr=1', '-crf', '35']
    elif codec == 'hevc':
        command += ['-c:v', 'libx265', '-preset', 'ultrafast', '-profile:v', profile,
                    '-x265-params', 'level-idc=4.1:high-tier=0:log-level=error:pools=1:frame-threads=1:bframes=0:keyint=3:info=0', '-crf', '35']
    else:
        command += ['-c:v', 'libvpx-vp9', '-profile:v', profile, '-deadline', 'realtime',
                    '-cpu-used', '8', '-threads', '1', '-lag-in-frames', '0', '-crf', '45', '-b:v', '0']
    command += [str(path)]
    subprocess.run(command, check=True, capture_output=True)
    data = path.read_bytes()
    probe = json.loads(subprocess.check_output(['ffprobe', '-v', 'error', '-show_streams', '-count_frames', '-of', 'json', str(path)], text=True))
    stream = probe['streams'][0]
    assert (stream['width'], stream['height'], stream['pix_fmt']) == (1920, 1080, pixel)
    if codec == 'hevc':
        assert stream['level'] == 123
    assert stream['nb_read_frames'] == '3'
    timing = {}
    if codec in ('h264', 'hevc'):
        trace = subprocess.run(['ffmpeg', '-hide_banner', '-i', str(path), '-c:v', 'copy',
                                '-bsf:v', 'trace_headers', '-f', 'null', '-'], check=True, capture_output=True, text=True).stderr
        fields = ('num_units_in_tick', 'time_scale', 'frame_mbs_only_flag') if codec == 'h264' else ('vui_num_units_in_tick', 'vui_time_scale', 'general_tier_flag')
        for field in fields:
            values = {int(v) for v in re.findall(r'\b' + field + r'\s+[01]+\s+= (\d+)', trace)}
            assert len(values) == 1, (field, values)
            timing[field] = values.pop()
        if codec == 'h264':
            assert timing['frame_mbs_only_flag'] == 1
            assert timing['time_scale'] == 120 * timing['num_units_in_tick']
        else:
            assert timing['general_tier_flag'] == 0
            assert timing['vui_time_scale'] == 60 * timing['vui_num_units_in_tick']
    else:
        assert stream['r_frame_rate'] == '60/1'
    assert stream['profile'] == {'h264': 'Constrained Baseline', 'main': 'Main', 'main10': 'Main 10', 'vp9_0': 'Profile 0', 'vp9_2': 'Profile 2'}[name]
    if codec == 'h264':
        assert stream['level'] == 42
    packets = []
    if codec == 'vp9':
        pos = 32
        while pos < len(data):
            size = struct.unpack_from('<I', data, pos)[0]
            pos += 12
            packets.append(data[pos:pos+size])
            pos += size
        assert len(packets) == 3 and pos == len(data)
    else:
        packet_info = json.loads(subprocess.check_output(['ffprobe', '-v', 'error', '-show_packets', '-of', 'json', str(path)], text=True))
        packets = [data[int(p['pos']):int(p['pos'])+int(p['size'])] for p in packet_info['packets']]
        assert len(packets) == 3 and b''.join(packets) == data
    for index, packet in enumerate(packets):
        header += [f'static const guint8 fixture_{name}_{index}[] = {{']
        header += [' ' + ','.join(f'0x{v:02x}' for v in packet[i:i+16]) + ',' for i in range(0, len(packet), 16)]
        header += ['};']
    header += [f'static const struct probe_packet fixture_{name}[] = {{']
    header += [f' {{fixture_{name}_{i}, sizeof(fixture_{name}_{i})}},' for i in range(len(packets))]
    header += ['};']
    rows.append({'name': name, 'command': command, 'sha256': hashlib.sha256(data).hexdigest(), 'bytes': len(data), 'ffprobe': probe, 'encoded_timing': timing, 'packet_sha256': [hashlib.sha256(p).hexdigest() for p in packets]})
(ROOT / 'capability-fixtures.h').write_text('\n'.join(header) + '\n')
(ROOT / 'tests/capability-fixtures.json').write_text(json.dumps({'license': 'CC0-1.0', 'source': 'FFmpeg lavfi testsrc2 (no external media)', 'ffmpeg': subprocess.check_output(['ffmpeg', '-version'], text=True).splitlines()[0], 'fixtures': rows}, indent=2) + '\n')
print([(row['name'], row['bytes']) for row in rows])
